### ISSUE TITLE
Audit requirement -- Section 7.3 of bylaws

### ISSUE THREAD

**Issue by thomasadler** [ZephyrTransport/governance#10]
A full annual audit requirement is both expensive and unnecessary for a nonprofit corporation at least until significant revenues/expenses begin.

The Standards for Excellence program, a comprehensive ethics and accountability program, recommends the following;
"Nonprofits reporting total annual revenues in excess of $500,000 should be subject to an audit by an independent Certified Public Accountant.  Organizations reporting total annual revenues in excess of $300,000 should be subject to a review of financial statements by an independent Certified Public Accountant. Organizations reporting total annual revenues in excess of $100,000 should have a compilation of financial statements prepared by an independent Certified Public Accountant."

**Comment by DavidOry** [comment]
Removed audit requirement in [this commit](https://github.com/ZephyrTransport/governance/commit/406fd222b4c0ca1461681679c54d8445267f4b7e). This will give board freedom to adhere to the standards of the choosing (while, of course, following the law).
