### ISSUE TITLE
Few individuals sentence

### ISSUE THREAD

**Issue by e-lo** [ZephyrTransport/governance#7]
`PMCs shall activitely discourage communities centered around a few individuals who work virtually uncontested for long periods. We believe that this is detrimental to the quality, relevance, and robustness of products and of the travel demand forecasting industry at large.`

1. Fix misspelling of "actively"
2. Given the small size of our community, it is likely some aspects will only have a “few” individuals capable of moving said item forward for a “long” period but then it depends how you define “few” and “long”.

**Comment by DavidOry** [comment]
It's still vague, but it seems useful as a guiding principle:

`... PMCs shall actively discourage communities centered around a two or three individuals who work without seeking broader input for long periods. We believe that this is detrimental to the quality, relevance, and robustness of products.`

**Comment by e-lo** [comment]
LGTM
